// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCJW8z9kSpieqkPvxOZ3GRxN_Fru4q6CA',
    appId: '1:709857563293:web:d43da4be9b3c20f9c3fa74',
    messagingSenderId: '709857563293',
    projectId: 'push-notification-app-76a4f',
    authDomain: 'push-notification-app-76a4f.firebaseapp.com',
    storageBucket: 'push-notification-app-76a4f.firebasestorage.app',
    measurementId: 'G-1P88MY0SFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC21VaYTK573_HTPB9eVXGLYP3UYZPCxX4',
    appId: '1:709857563293:android:1a2c9c2d6c70dd6ac3fa74',
    messagingSenderId: '709857563293',
    projectId: 'push-notification-app-76a4f',
    storageBucket: 'push-notification-app-76a4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAygXtYaIm05E-eAy0W5yNweCrzsQxeV0M',
    appId: '1:709857563293:ios:a4888813d5dfece8c3fa74',
    messagingSenderId: '709857563293',
    projectId: 'push-notification-app-76a4f',
    storageBucket: 'push-notification-app-76a4f.firebasestorage.app',
    iosBundleId: 'com.example.pushNotificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAygXtYaIm05E-eAy0W5yNweCrzsQxeV0M',
    appId: '1:709857563293:ios:a4888813d5dfece8c3fa74',
    messagingSenderId: '709857563293',
    projectId: 'push-notification-app-76a4f',
    storageBucket: 'push-notification-app-76a4f.firebasestorage.app',
    iosBundleId: 'com.example.pushNotificationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCJW8z9kSpieqkPvxOZ3GRxN_Fru4q6CA',
    appId: '1:709857563293:web:8e1ef817c8110031c3fa74',
    messagingSenderId: '709857563293',
    projectId: 'push-notification-app-76a4f',
    authDomain: 'push-notification-app-76a4f.firebaseapp.com',
    storageBucket: 'push-notification-app-76a4f.firebasestorage.app',
    measurementId: 'G-MGP2JEML5Q',
  );
}
